name: aacademic
description: A free and feature-rich AAC (Augmentative Alternative Communication) application that is available on both iOS and Android.


version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera:
  path_provider:
  path:
  image_picker: ^0.8.4+2
  provider: ^6.0.5
  easy_localization: ^3.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_core: ^2.6.1
  firebase_auth: ^4.2.9
  cloud_firestore: ^4.4.2
  firebase_performance: ^0.9.0+13
  firebase_storage: ^11.0.14
  flutter_tts:
  settings_ui: ^2.0.2
  google_sign_in: ^6.0.2
  flutter_pw_validator: ^1.5.0


dependency_overrides:
  camera_avfoundation: 0.9.7+1
  flutter_translate:
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^3.0.0
  flutter_colorpicker: ^1.0.3
  flutter_staggered_grid_view:
  flutter_image_compress: ^1.1.3
  image:
  tflite:
  camera_android:
    git:
      url: https://github.com/bottlepay/plugins.git
      path: packages/camera/camera_android
      ref: e1a4dba770da9bc3cf9f858bac6837083f8b9059



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  
  assets:
  - assets/

    #logos
  - assets/logos/logo.png
  - assets/logos/google.png
  - assets/translations/en-US.json
  - assets/translations/es-ES.json
  
flutter_launch_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/Aacai_2.png"
    min_sdk_android: 28